# Generated by Django 4.1.7 on 2023-03-14 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taha_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teacher",
            old_name="address",
            new_name="skills",
        ),
    ]
