# Generated by Django 4.1.7 on 2023-03-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taha_api", "0002_rename_address_teacher_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="featured_img",
            field=models.ImageField(null=True, upload_to="featured_img/"),
        ),
        migrations.AddField(
            model_name="course",
            name="techs",
            field=models.TextField(null=True),
        ),
    ]
