# Generated by Django 4.1.7 on 2023-04-08 09:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("taha_api", "0005_rename_phone_no_student_username_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chapter",
            options={"verbose_name_plural": "Chapters"},
        ),
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name_plural": "Courses"},
        ),
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name_plural": "Students"},
        ),
        migrations.AddField(
            model_name="teacher",
            name="details",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="EnrollCourseStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enrolled_time", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrolled_courses",
                        to="taha_api.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrolled_students",
                        to="taha_api.student",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Enrolled Courses",
            },
        ),
    ]
