# Generated by Django 4.1.7 on 2023-04-19 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "taha_api",
            "0008_rename_details_teacher_bio_remove_teacher_phone_no_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AddToFav",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=False)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="taha_api.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="taha_api.student",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Add to Favourite",
            },
        ),
    ]
