# Generated by Django 4.1.7 on 2023-04-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taha_api", "0011_remove_courserating_status_addtofav"),
    ]

    operations = [
        migrations.AddField(
            model_name="courserating",
            name="status",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="AddToFav",
        ),
    ]
