# Generated by Django 4.1.7 on 2023-04-20 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taha_api", "0014_studentassignment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentassignment",
            options={"verbose_name_plural": "Student Assignments"},
        ),
        migrations.RenameField(
            model_name="studentassignment",
            old_name="teacher",
            new_name="created_by",
        ),
        migrations.RenameField(
            model_name="studentassignment",
            old_name="student",
            new_name="created_for",
        ),
    ]
