# Generated by Django 4.1.7 on 2023-04-20 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taha_api", "0015_alter_studentassignment_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentassignment",
            old_name="created_for",
            new_name="student",
        ),
        migrations.RenameField(
            model_name="studentassignment",
            old_name="created_by",
            new_name="teacher",
        ),
    ]
