# Generated by Django 4.1.7 on 2023-04-21 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("taha_api", "0016_rename_created_for_studentassignment_student_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentassignment",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="taha_api.course",
            ),
        ),
    ]
