# Generated by Django 4.1.7 on 2023-04-21 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("taha_api", "0017_studentassignment_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentassignment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="taha_api.course"
            ),
        ),
    ]
