# Generated by Django 4.1.7 on 2023-04-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taha_api", "0018_alter_studentassignment_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentassignment",
            name="assignment_status",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
