# Generated by Django 4.1.7 on 2023-04-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taha_api", "0019_studentassignment_assignment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="profile_img",
            field=models.ImageField(null=True, upload_to="student/profile_img/"),
        ),
        migrations.AlterField(
            model_name="student",
            name="password",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
