# Generated by Django 4.1.7 on 2023-04-26 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taha_api", "0020_student_profile_img_alter_student_password"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="intereseted_cat",
            new_name="interested_cat",
        ),
    ]
