# Generated by Django 4.1.7 on 2023-05-26 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("taha_api", "0025_coursequizs_delete_coursequiz"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttemtedQuestions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attemted_time", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="taha_api.quizquestions",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="taha_api.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Attemted Questions",
            },
        ),
    ]
