# Generated by Django 4.1.7 on 2023-05-26 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taha_api", "0026_attemtedquestions"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AttemtedQuestions",
            new_name="AttemtedQuiz",
        ),
        migrations.AlterModelOptions(
            name="attemtedquiz",
            options={"verbose_name_plural": "Attemted Quiz"},
        ),
    ]
