# Generated by Django 4.1.7 on 2023-05-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taha_api", "0027_rename_attemtedquestions_attemtedquiz_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attemtedquiz",
            name="right_ans",
            field=models.CharField(default=1, max_length=50),
        ),
    ]
