# Generated by Django 4.1.7 on 2023-05-26 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taha_api", "0031_alter_attemptquiz_options_alter_attemptquiz_student"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attemptquiz",
            old_name="right_ans",
            new_name="submitted_ans",
        ),
    ]
