# Generated by Django 4.1.7 on 2023-05-26 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("taha_api", "0032_rename_right_ans_attemptquiz_submitted_ans"),
    ]

    operations = [
        migrations.AddField(
            model_name="attemptquiz",
            name="quiz",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="taha_api.quiz",
            ),
        ),
    ]
